models/User.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class User(db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)
    email = db.Column(db.String)    
    age = db.Column(db.String(120))
    address = db.Column(db.String(120))
    
    @property
    def serialize(self):
        return {
            'id': self.id,
            'name': self.name,
            'email': self.email,
            'age': self.age,
            'address': self.address
        }

app.py
from flask import Flask, render_template
from flask_migrate import Migrate
from models.User import db
from routes.user_bp import user_bp

app = Flask(__name__)
app.config.from_object('config')

app.url_map.strict_slashes = False

db.init_app(app)
migrate = Migrate(app, db)

app.register_blueprint(user_bp, url_prefix='/users')

@app.route('/')
def index():
    return render_template('index.j2')

if __name__ == '__main__':
    app.debug = True
    app.run()

controllers/UserController.py
# pseudo code
from flask import render_template, redirect, url_for, request, abort, flash
from models.User import User
from flask_sqlalchemy import SQLAlchemy
db = SQLAlchemy()

def index():
    users = User.query.all()
    return render_template('user/index_user.j2', users=users)

def store():
    if request.method == 'POST':
        if not request.form['name'] or not request.form['email'] or not request.form['address'] or not request.form['age']:
            flash('Por favor ingresa todos los campos', 'error')
        else:
            name = request.values.get('name') 
            email = request.values.get('email') 
            address = request.values.get('address') 
            age = request.values.get('age') 

            objUser = User()
            objUser.name = name
            objUser.email = email
            objUser.address = address
            objUser.age = age

            db.session.add(objUser)
            db.session.commit()

            flash('Usuario registrado correctamente!', 'info')

        return render_template('user/create_user.j2')
    
    return render_template('user/create_user.j2')

def show(userId):
    ...

def update(userId):
    ...

def delete(userId):
    ...

routes/user_bp.py
from flask import Blueprint
from controllers.UserController import index, store, show, update, delete

user_bp = Blueprint('user_bp', __name__)

user_bp.route('', methods=['GET'])(index)
user_bp.route('/create', methods=['GET', 'POST'])(store)
user_bp.route('/<int:user_id>', methods=['GET'])(show)
user_bp.route('/<int:user_id>/edit', methods=['POST'])(update)
user_bp.route('/<int:user_id>', methods=['DELETE'])(delete)

templates/base.j2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://unpkg.com/@tailwindcss/forms@0.3.4/dist/forms.min.css" rel="stylesheet">

    <script>
        tailwind.config = {
        theme: {
            extend: {
            colors: {
                clifford: '#da373d',
            }
            }
        }
        }
    </script>

    <title>{% block title %} {% endblock %} - FlaskApp</title>
    
</head>
<body>
    <div class="min-h-full">
        <nav class="bg-gray-800">
            <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div class="flex items-center justify-between h-16">
                <div class="flex items-center">
                <div class="flex-shrink-0">
                    <img class="h-8 w-8" src="https://tailwindui.com/img/logos/workflow-mark-indigo-500.svg" alt="Workflow">
                </div>
                <div class="hidden md:block">
                    <div class="ml-10 flex items-baseline space-x-4">
                    {% include "partials/navigation.j2" %}
                    </div>
                </div>
                </div>

            </div>
            </div>
        </nav>

        {% include "partials/flash_message.j2" %}

        <main class="bg-gray-100">
            <div class="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
            <!-- Replace with your content -->
                {% block content %} {% endblock %}      
            <!-- /End replace -->
            </div>
        </main>

    </div>
  
</body>
</html>

templates/index.j2
{% extends 'base.j2' %}

{% block title %} Index Title {% endblock %}

<header class="bg-white shadow">
    <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
        <h1 class="text-3xl font-bold text-gray-900">Index</h1>
    </div>
</header>

{% block content %}    


<div class="px-4 py-6 sm:px-0">
        <div class="border-4 border-gray-200 rounded-lg h-96">
            Welcome to FlaskApp!
        </div>
      </div>

{% endblock %}

templates/partials/flash_message.j2
{% for category, message in get_flashed_messages(with_categories = true) %}
    {% if category == "info" %}
        <div class="p-4 mb-4 text-sm text-green-700 bg-green-100 rounded-lg dark:bg-green-200 dark:text-green-800" role="alert">
            <span class="font-medium">Info :</span> {{ message }}
        </div>            
    {% elif category == "error" %}
        <div class="p-4 mb-4 text-sm text-red-700 bg-red-100 rounded-lg dark:bg-red-200 dark:text-red-800" role="alert">
            <span class="font-medium">Error :</span> {{ message }}
        </div>
    {% elif category == "warning" %}
        <div class="p-4 mb-4 text-sm text-yellow-700 bg-yellow-100 rounded-lg dark:bg-yellow-200 dark:text-yellow-800" role="alert">
            <span class="font-medium">Warning :</span> {{ message }}
        </div>
    {% elif category == "dark-error" %}
        <div class="p-4 text-sm text-gray-700 bg-gray-100 rounded-lg dark:bg-gray-700 dark:text-gray-300" role="alert">
            <span class="font-medium">Dark Error :</span> {{ message }}
        </div>
    {% endif %}
{% endfor %}

templates/partials/navigation.j2
<!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
{% if url_for(request.endpoint) == "/" %}
    <a href="/"                              class="bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium">Home</a>
    <a href="{{ url_for('user_bp.index') }}" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">UserList</a>
    <a href="{{ url_for('user_bp.store') }}" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">CreateUser</a>
{% elif url_for(request.endpoint) == "/users" %}
    <a href="/"                              class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Home</a>
    <a href="{{ url_for('user_bp.index') }}" class="bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium">UserList</a>
    <a href="{{ url_for('user_bp.store') }}" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">CreateUser</a>
{% elif url_for(request.endpoint) == "/users/create" %}
    <a href="/"                              class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Home</a>
    <a href="{{ url_for('user_bp.index') }}" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">UserList</a>
    <a href="{{ url_for('user_bp.store') }}" class="bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium">CreateUser</a>
{% endif %}

templates/user/create_user.j2
{% extends 'base.j2' %}

{% block title %} Create Users {% endblock %}
{% block content %}
    <div class="md:grid md:grid-cols-3 md:gap-6">
        <div class="md:col-span-1">
            <div class="px-4 sm:px-0">
            <h3 class="text-lg font-medium leading-6 text-gray-900">Creación de Usuario</h3>
            <p class="mt-1 text-sm text-gray-600">Ingresa todos los datos de usuario.</p>
            </div>
        </div>
        <div class="mt-5 md:mt-0 md:col-span-2">
            <form action="{{ url_for('user_bp.store') }}" method="POST">
                <div class="shadow sm:rounded-md sm:overflow-hidden">
                    <div class="px-4 py-5 bg-white space-y-6 sm:p-6">
                        <div class="grid grid-cols-3 gap-6">
                            <div class="col-span-3 sm:col-span-2">
                            <label for="company-website" class="block text-sm font-medium text-gray-700"> Nombre </label>
                            <div class="mt-1 flex rounded-md shadow-sm">
                                <input type="text" name="name" id="name" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" placeholder="Nombre">
                            </div>
                            </div>
                        </div>
                        <div class="grid grid-cols-3 gap-6">
                            <div class="col-span-3 sm:col-span-2">
                            <label for="company-website" class="block text-sm font-medium text-gray-700"> Website </label>
                            <div class="mt-1 flex rounded-md shadow-sm">
                                <input type="text" name="email" id="email" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" placeholder="demo@mail.com">
                            </div>
                            </div>
                        </div>
                        <div class="grid grid-cols-3 gap-6">
                            <div class="col-span-3 sm:col-span-2">
                            <label for="company-website" class="block text-sm font-medium text-gray-700"> Website </label>
                            <div class="mt-1 flex rounded-md shadow-sm">
                                <input type="text" name="address" id="address" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" placeholder="Av. Larco 123">
                            </div>
                            </div>
                        </div>
                        <div class="grid grid-cols-3 gap-6">
                            <div class="col-span-3 sm:col-span-2">
                            <label for="company-website" class="block text-sm font-medium text-gray-700"> Website </label>
                            <div class="mt-1 flex rounded-md shadow-sm">
                                <input type="text" name="age" id="age" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" placeholder="22">
                            </div>
                            </div>
                        </div>
                    </div>
                    <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
                        <button type="submit" class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                            Save
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/user/index_user.j2
{% extends 'base.j2' %}

{% block title %} Index Users {% endblock %}
{% block content %}    
    <h1>Listado de Usuarios</h1>
    <hr>

    {% if (users | length)>0 %}
        <div class="overflow-x-auto relative shadow sm:rounded-md">
            <table class="w-full text-sm text-left text-gray-500">
                <thead class="text-xs text-gray-500 uppercase bg-gray-150 border-gray-800">
                    <tr>
                        <th scope="col" class="py-3 px-6">
                            Nombre
                        </th>
                        <th scope="col" class="py-3 px-6">
                            Email
                        </th>
                        <th scope="col" class="py-3 px-6">
                            Edad
                        </th>
                        <th scope="col" class="py-3 px-6">
                            Dirección
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in users %}
                        {% if loop.index % 2 == 0 %}
                            {% set bg_color = 'bg-white' %}
                        {% else %}
                            {% set bg_color = 'bg-yellow-50' %}
                        {% endif %}
            
                        <tr class="{{ bg_color }} border-b">
                            <th scope="row" class="py-4 px-6 font-medium text-gray-900 whitespace-nowrap">
                                {{ user.name | upper }}
                            </th>
                            <td class="py-4 px-6">
                                {{ user.email | upper }}
                            </td>
                            <td class="py-4 px-6">
                                {{ user.age | upper }}
                            </td>
                            <td class="py-4 px-6">
                                {{ user.address | upper }}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <hr>
        <div>
            <p>{{ users | join(" | ") }}</p>
        </div>

    {% else %}
        <div style="width: 50%; margin: auto"> 
            No se encuentran datos
        </div>
    {% endif %}

{% endblock %}